using System.Text;

namespace Reflector
{
    static class Emitter
    {
        public static string Emit(string originalPath, List<TypeModel> types, List<EnumModel> enums, List<TypeModel> allTypes, string? baseDir = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED by Reflector — do not edit by hand");
            sb.AppendLine("#pragma once");
            sb.AppendLine();
            sb.AppendLine("#include \"Chicane/Core/Reflection/Enum/AutoRegister.hpp\"");
            sb.AppendLine("#include \"Chicane/Core/Reflection/Type/AutoRegister.hpp\"");
            sb.AppendLine();

            var includePath = baseDir != null
                ? Path.GetRelativePath(baseDir, originalPath).Replace('\\', '/')
                : Path.GetFileName(originalPath);

            sb.AppendLine($"#include \"{includePath}\"");
            sb.AppendLine();

            foreach (var e in enums)
            {
                EmitEnum(sb, e);
            }

            foreach (var t in types)
            {
                EmitType(sb, t, allTypes);
            }

            return sb.ToString();
        }

        static string SafeIdentifier(string qualifiedName)
            => qualifiedName.Replace("::", "_");

        static string EmitAnyCast(string typeName, string expr)
        {
            if (typeName.EndsWith('*'))
            {
                return $"static_cast<{typeName}>(std::any_cast<void*>({expr}))";
            }

            return $"std::any_cast<{typeName}>({expr})";
        }

        static void EmitEnum(StringBuilder sb, EnumModel e)
        {
            sb.AppendLine($"inline Chicane::ReflectionEnumAutoRegister _reg_enum_{SafeIdentifier(e.Name)}(");
            sb.AppendLine($"\t{{");
            sb.AppendLine($"\t\t\"{e.Name}\",");

            sb.AppendLine("\t\t{");
            foreach (var en in e.Enumerators)
            {
                sb.AppendLine($"\t\t\t{{");
                sb.AppendLine($"\t\t\t\t\"{en.Name}\",");
                sb.AppendLine($"\t\t\t\tstatic_cast<int>({e.Name}::{en.Name})");
                sb.AppendLine($"\t\t\t}},");
            }
            sb.AppendLine("\t\t}");

            sb.AppendLine("\t}");
            sb.AppendLine(");");
            sb.AppendLine();
        }

        static string EmitIterable(string containerType, bool isIterable, string elementName, bool isElementPointer)
        {
            if (!isIterable || string.IsNullOrEmpty(elementName))
            {
                return "\t\t\t\tChicane::ReflectionFieldIterable()\n";
            }

            string element = isElementPointer
                ? $"\t\t\t\t\t\treturn static_cast<const {containerType}*>(inContainer)->at(inIndex);\n"
                : $"\t\t\t\t\t\treturn &static_cast<const {containerType}*>(inContainer)->at(inIndex);\n";

            return (
                $"\t\t\t\tChicane::ReflectionFieldIterable(\n" +
                $"\t\t\t\t\t\"{elementName}\",\n" +
                $"\t\t\t\t\tstd::type_index(typeid({elementName})),\n" +
                $"\t\t\t\t\tsizeof({elementName}),\n" +
                $"\t\t\t\t\t[](const void* inContainer)\n" +
                $"\t\t\t\t\t{{\n" +
                $"\t\t\t\t\t\treturn static_cast<const {containerType}*>(inContainer)->size();\n" +
                $"\t\t\t\t\t}},\n" +
                $"\t\t\t\t\t[](const void* inContainer, std::size_t inIndex) -> const void*\n" +
                $"\t\t\t\t\t{{\n" +
                element +
                $"\t\t\t\t\t}},\n" +
                $"\t\t\t\t\t[](const void* inContainer, std::any& outSnapshot) -> const void*\n" +
                $"\t\t\t\t\t{{\n" +
                $"\t\t\t\t\t\toutSnapshot = *static_cast<const {containerType}*>(inContainer);\n" +
                $"\t\t\t\t\t\treturn std::any_cast<{containerType}>(&outSnapshot);\n" +
                $"\t\t\t\t\t}}\n" +
                $"\t\t\t\t)\n"
            );
        }

        static string EmitMethodContainerResolver(FunctionModel f)
        {
            if (!f.IsIterable)
            {
                return "\t\t\t\t{}";
            }

            return (
                $"\t\t\t\t[](const std::any& inValue) -> const void*\n" +
                $"\t\t\t\t{{\n" +
                $"\t\t\t\t\treturn std::any_cast<{f.ReturnType}>(&inValue);\n" +
                $"\t\t\t\t}}"
            );
        }

        static void EmitType(StringBuilder sb, TypeModel t, List<TypeModel> allTypes)
        {
            var safeId = SafeIdentifier(t.Name);

            sb.AppendLine("#if defined(__GNUC__) || defined(__clang__)");
            sb.AppendLine("#   pragma GCC diagnostic push");
            sb.AppendLine("#   pragma GCC diagnostic ignored \"-Winvalid-offsetof\"");
            sb.AppendLine("#endif");
            sb.AppendLine();

            sb.AppendLine($"inline Chicane::ReflectionTypeAutoRegister _reg_{safeId}(");
            sb.AppendLine($"\tChicane::ReflectionTypeInfo(");
            sb.AppendLine($"\t\t\"{t.Name}\",");
            sb.AppendLine($"\t\tsizeof({t.Name}),");
            sb.AppendLine($"\t\tstd::type_index(typeid({t.Name})),");

            sb.AppendLine("\t\t{");
            foreach (ConstructorModel c in t.Constructors)
            {
                var paramUnpack = string.Join(",", c.ParamTypes.Select((p, i) => $"\n\t\t\t\t\t\t{EmitAnyCast(p, $"inParams.at({i})")}"));

                if (c.ParamTypes.Count() > 0)
                {
                    paramUnpack += "\n\t\t\t\t\t";
                }

                sb.AppendLine(
                    $"\t\t\t[](std::vector<std::any> inParams)\n" +
                    $"\t\t\t{{\n" +
                    $"\t\t\t\tif (inParams.size() < {c.ParamTypes.Count()})\n" +
                    $"\t\t\t\t{{\n" +
                    $"\t\t\t\t\tthrow std::runtime_error(\"Missing reflected constructor [{t.Name}] parameters [{string.Join(", ", c.ParamTypes)}]\");\n" +
                    $"\t\t\t\t}}\n" +
                    $"\t\n" +
                    $"\t\t\t\treturn static_cast<void*>(\n" +
                    $"\t\t\t\t\tnew {t.Name}({paramUnpack})\n" +
                    $"\t\t\t\t);\n" +
                    $"\t\t\t}},"
                );
            }
            sb.AppendLine("\t\t},");

            sb.AppendLine("\t\t{");
            foreach (FunctionModel f in t.Functions)
            {
                var paramUnpack = string.Join(",", f.ParamTypes.Select((p, i) => $"\n\t\t\t\t\t\t{EmitAnyCast(p, $"inParams.at({i})")}"));
                var paramChecker = "";

                if (f.ParamTypes.Count() > 0)
                {
                    paramUnpack += "\n\t\t\t\t\t";

                    paramChecker = (
                        $"\t\t\t\t\tif (inParams.size() < {f.ParamTypes.Count()})\n" +
                        $"\t\t\t\t\t{{\n" +
                        $"\t\t\t\t\t\tthrow std::runtime_error(\"Missing reflected method [{f.Name}] parameters [{string.Join(", ", f.ParamTypes)}]\");\n" +
                        $"\t\t\t\t\t}}\n" +
                        $"\t\n"
                    );
                }

                bool isVoid = f.ReturnType == "void";
                string call = isVoid
                    ? $"\t\t\t\t\tstatic_cast<{t.Name}*>(inInstance)->{f.Name}({paramUnpack});\n" +
                      $"\t\t\t\t\treturn {{}};\n"
                    : $"\t\t\t\t\treturn static_cast<{t.Name}*>(inInstance)->{f.Name}({paramUnpack});\n";

                string returnTypeIndex = isVoid
                    ? "std::nullopt"
                    : $"std::type_index(typeid({f.ReturnType}))";
                string elementIndex = string.IsNullOrEmpty(f.ElementName)
                    ? "std::nullopt"
                    : $"std::type_index(typeid({f.ElementName}))";
                string returnSize = isVoid ? "0" : $"sizeof({f.ReturnType})";

                sb.AppendLine(
                    $"\t\t\t{{\n" +
                    $"\t\t\t\t\"{f.Name}\",\n" +
                    $"\t\t\t\t\"{f.ReturnType}\",\n" +
                    $"\t\t\t\t{{{string.Join(" ,", f.ParamTypes.Select(p => $"\"{p}\""))}}},\n" +
                    $"\t\t\t\t[](void* inInstance, std::vector<std::any> inParams) -> std::any\n" +
                    $"\t\t\t\t{{\n" +
                    paramChecker +
                    call +
                    $"\t\t\t\t}},\n" +
                    $"\t\t\t\t{(f.IsIterable ? "true" : "false")},\n" +
                    $"\t\t\t\t{returnTypeIndex},\n" +
                    $"\t\t\t\t{elementIndex},\n" +
                    $"\t\t\t\t{returnSize},\n" +
                    EmitIterable(f.ReturnType, f.IsIterable, f.ElementName, f.IsElementPointer) +
                    $",\n" +
                    EmitMethodContainerResolver(f) + "\n" +
                    $"\t\t\t}},"
                );
            }
            sb.AppendLine("\t\t},");

            sb.AppendLine("\t\t{");
            foreach (FieldModel f in t.Fields)
            {
                if (f.Names.Count <= 0)
                {
                    continue;
                }

                bool isReflected = allTypes.Any(rt => rt.Name == f.TypeName);

                sb.AppendLine(
                    $"\t\t\t{{\n" +
                    $"\t\t\t\t{{{string.Join(" ,", f.Names.Select(p => $"\"{p}\""))}}},\n" +
                    $"\t\t\t\t\"{f.TypeName}\",\n" +
                    $"\t\t\t\toffsetof({t.Name}, {f.Name}),\n" +
                    $"\t\t\t\tsizeof({(f.IsPointer ? "void*" : f.TypeName)}),\n" +
                    $"\t\t\t\tstd::type_index(typeid({f.TypeName})),\n" +
                    $"\t\t\t\t{(isReflected ? "true" : "false")},\n" +
                    $"\t\t\t\t{(f.IsPointer ? "true" : "false")},\n" +
                    $"\t\t\t\t{(f.IsIterable ? "true" : "false")},\n" +
                    $"\t\t\t\t{(string.IsNullOrEmpty(f.ElementName) ? "std::nullopt" : $"std::type_index(typeid({f.ElementName}))")},\n" +
                    EmitIterable(f.TypeName, f.IsIterable, f.ElementName, f.IsElementPointer) +
                    $"\t\t\t}},"
                );
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine("\t)");
            sb.AppendLine(");");
            sb.AppendLine();

            sb.AppendLine("#if defined(__GNUC__) || defined(__clang__)");
            sb.AppendLine("#   pragma GCC diagnostic pop");
            sb.AppendLine("#endif");
            sb.AppendLine();
        }
    }
}