using System.Text;

namespace Reflector
{
    static class Emitter
    {
        public static string Emit(
            string originalPath,
            List<TypeModel> types,
            List<EnumModel> enums,
            Dictionary<string, string>? externalTypes = null,
            string? baseDir = null
        )
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED by Reflector — do not edit by hand");
            sb.AppendLine("#pragma once");
            sb.AppendLine();

            var includePath = baseDir != null
                ? Path.GetRelativePath(baseDir, originalPath).Replace('\\', '/')
                : Path.GetFileName(originalPath);

            sb.AppendLine($"#include \"{includePath}\"");
            sb.AppendLine();

            var reflectedTypes = types.ToDictionary(
                t => t.Name,
                t => QualifiedName(t.Namespace, t.Name)
            );

            if (externalTypes != null)
            {
                foreach (var kv in externalTypes)
                {
                    reflectedTypes.TryAdd(kv.Key, kv.Value);
                }
            }

            foreach (var e in enums)
            {
                EmitEnum(sb, e);
            }

            foreach (var t in types)
            {
                EmitType(sb, t, reflectedTypes);
            }

            return sb.ToString();
        }

        static string QualifiedName(string? ns, string name)
        {
            if (string.IsNullOrWhiteSpace(ns))
            {
                return name;
            }

            return $"{ns}::{name}";
        }

        static string ResolveFieldType(string fieldTypeName, Dictionary<string, string> reflectedTypes)
        {
            if (fieldTypeName.Contains("::"))
            {
                return fieldTypeName;
            }

            if (reflectedTypes.TryGetValue(fieldTypeName, out var qualified))
            {
                return qualified;
            }

            return fieldTypeName;
        }

        static string SafeIdentifier(string qualifiedName)
            => qualifiedName.Replace("::", "_");

        static void EmitEnum(StringBuilder sb, EnumModel e)
        {
            var qualifiedName = QualifiedName(e.Namespace, e.Name);

            sb.AppendLine($"// ── Enum: {qualifiedName}");
            sb.AppendLine($"inline Chicane::ReflectionEnumAutoRegister _reg_enum_{SafeIdentifier(qualifiedName)}(Chicane::ReflectionEnumInfo{{");
            sb.AppendLine($"    \"{qualifiedName}\",");
            sb.AppendLine("    {");

            foreach (var en in e.Enumerators)
                sb.AppendLine($"        {{ \"{en.Name}\", static_cast<int>({qualifiedName}::{en.Name}) }},");

            sb.AppendLine("    }");
            sb.AppendLine("});\n");
        }

        static void EmitType(StringBuilder sb, TypeModel t, Dictionary<string, string> reflectedTypes)
        {
            var qualifiedName = QualifiedName(t.Namespace, t.Name);
            var safeId = SafeIdentifier(qualifiedName);

            sb.AppendLine($"// ── {char.ToUpper(t.Kind[0])}{t.Kind[1..]}: {qualifiedName}");

            sb.AppendLine("#if defined(__GNUC__) || defined(__clang__)");
            sb.AppendLine("#   pragma GCC diagnostic push");
            sb.AppendLine("#   pragma GCC diagnostic ignored \"-Winvalid-offsetof\"");
            sb.AppendLine("#endif");
            sb.AppendLine();

            sb.AppendLine($"inline Chicane::ReflectionTypeAutoRegister _reg_{safeId}(Chicane::ReflectionTypeInfo{{");
            sb.AppendLine($"    \"{qualifiedName}\",");
            sb.AppendLine($"    sizeof({qualifiedName}),");
            sb.AppendLine($"    std::type_index(typeid({qualifiedName})),");
            sb.AppendLine("    { // fields");

            foreach (var f in t.Fields)
            {
                var resolvedType = ResolveFieldType(f.TypeName, reflectedTypes);
                bool isReflected = reflectedTypes.ContainsKey(f.TypeName) ||
                                   reflectedTypes.ContainsValue(f.TypeName);

                sb.AppendLine(
                    $"        {{ \"{f.Name}\", \"{f.TypeName}\", " +
                    $"offsetof({qualifiedName}, {f.Name}), sizeof({(f.IsPointer ? "void*" : resolvedType)}), " +
                    $"std::type_index(typeid({resolvedType})), {(isReflected ? "true" : "false")}, " +
                    $"{(f.IsPointer ? "true" : "false")} }},"
                );
            }

            sb.AppendLine("    },");
            sb.AppendLine("    { // methods");

            foreach (var m in t.Methods)
            {
                sb.AppendLine($"        {{ \"{m.Name}\", \"{m.ReturnType}\", {{}},");
                sb.AppendLine($"          [](void* _i) {{ static_cast<{qualifiedName}*>(_i)->{m.Name}(); }} }},");
            }

            sb.AppendLine("    }");
            sb.AppendLine("});\n");

            sb.AppendLine("#if defined(__GNUC__) || defined(__clang__)");
            sb.AppendLine("#   pragma GCC diagnostic pop");
            sb.AppendLine("#endif");
            sb.AppendLine();
        }
    }
}