using System.Text;

namespace Reflector
{
    static class Emitter
    {
        public static string Emit(string originalPath, List<TypeModel> types, List<EnumModel> enums)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED by ReflectTool — do not edit by hand");
            sb.AppendLine("#pragma once");
            sb.AppendLine($"#include \"{Path.GetFileName(originalPath)}\"");
            sb.AppendLine();

            foreach (var e in enums) EmitEnum(sb, e);
            foreach (var t in types) EmitType(sb, t);
            return sb.ToString();
        }

        static void EmitEnum(StringBuilder sb, EnumModel e)
        {
            sb.AppendLine($"// ── Enum: {e.Name}");
            sb.AppendLine($"inline AutoRegisterEnum _reg_enum_{e.Name}(EnumInfo{{");
            sb.AppendLine($"    \"{e.Name}\",");
            sb.AppendLine("    {");
            foreach (var en in e.Enumerators)
                sb.AppendLine($"        {{ \"{en.Name}\", {en.Value} }},");
            sb.AppendLine("    }");
            sb.AppendLine("});\n");
        }

        static void EmitType(StringBuilder sb, TypeModel t)
        {
            sb.AppendLine($"// ── {char.ToUpper(t.Kind[0])}{t.Kind[1..]}: {t.Name}");
            sb.AppendLine($"inline AutoRegisterType _reg_{t.Name}(TypeInfo{{");
            sb.AppendLine($"    \"{t.Name}\", sizeof({t.Name}),");
            sb.AppendLine("    { // fields");
            foreach (var f in t.Fields)
                sb.AppendLine($"        {{ \"{f.Name}\", \"{f.TypeName}\", offsetof({t.Name}, {f.Name}), sizeof({f.TypeName}) }},");
            sb.AppendLine("    },");
            sb.AppendLine("    { // methods");
            foreach (var m in t.Methods)
            {
                sb.AppendLine($"        {{ \"{m.Name}\", \"{m.ReturnType}\", {{}},");
                sb.AppendLine($"          [](void* _i) {{ static_cast<{t.Name}*>(_i)->{m.Name}(); }} }},");
            }
            sb.AppendLine("    }");
            sb.AppendLine("});\n");
        }
    }
}