using System.Text;

namespace Reflector
{
    static class Emitter
    {
        public static string Emit(string originalPath, List<TypeModel> types, List<EnumModel> enums, List<TypeModel> allTypes, string? baseDir = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED by Reflector — do not edit by hand");
            sb.AppendLine("#pragma once");
            sb.AppendLine();
            sb.AppendLine("#include \"Chicane/Core/Reflection/Enum/AutoRegister.hpp\"");
            sb.AppendLine("#include \"Chicane/Core/Reflection/Type/AutoRegister.hpp\"");
            sb.AppendLine();

            var includePath = baseDir != null
                ? Path.GetRelativePath(baseDir, originalPath).Replace('\\', '/')
                : Path.GetFileName(originalPath);

            sb.AppendLine($"#include \"{includePath}\"");
            sb.AppendLine();

            foreach (var e in enums)
            {
                EmitEnum(sb, e);
            }

            foreach (var t in types)
            {
                EmitType(sb, t, allTypes);
            }

            return sb.ToString();
        }

        static string SafeIdentifier(string qualifiedName)
            => qualifiedName.Replace("::", "_");

        static void EmitEnum(StringBuilder sb, EnumModel e)
        {
            sb.AppendLine($"inline Chicane::ReflectionEnumAutoRegister _reg_enum_{SafeIdentifier(e.Name)}(");
            sb.AppendLine($"\t{{");
            sb.AppendLine($"\t\t\"{e.Name}\",");

            sb.AppendLine("\t\t{");
            foreach (var en in e.Enumerators)
            {
                sb.AppendLine($"\t\t\t{{");
                sb.AppendLine($"\t\t\t\t\"{en.Name}\",");
                sb.AppendLine($"\t\t\t\tstatic_cast<int>({e.Name}::{en.Name})");
                sb.AppendLine($"\t\t\t}},");
            }
            sb.AppendLine("\t\t}");

            sb.AppendLine("\t}");
            sb.AppendLine(");");
            sb.AppendLine();
        }

        static void EmitType(StringBuilder sb, TypeModel t, List<TypeModel> allTypes)
        {
            var safeId = SafeIdentifier(t.Name);

            sb.AppendLine("#if defined(__GNUC__) || defined(__clang__)");
            sb.AppendLine("#   pragma GCC diagnostic push");
            sb.AppendLine("#   pragma GCC diagnostic ignored \"-Winvalid-offsetof\"");
            sb.AppendLine("#endif");
            sb.AppendLine();

            sb.AppendLine($"inline Chicane::ReflectionTypeAutoRegister _reg_{safeId}(");
            sb.AppendLine($"\tChicane::ReflectionTypeInfo(");
            sb.AppendLine($"\t\t\"{t.Name}\",");
            sb.AppendLine($"\t\tsizeof({t.Name}),");
            sb.AppendLine($"\t\tstd::type_index(typeid({t.Name})),");

            sb.AppendLine("\t\t{");
            foreach (ConstructorModel c in t.Constructors)
            {
                var paramUnpack = string.Join(",", c.ParamTypes.Select((p, i) => $"\n\t\t\t\t\t\tstd::any_cast<{p}>(inParams.at({i}))"));

                if (c.ParamTypes.Count() > 0)
                {
                    paramUnpack += "\n\t\t\t\t\t";
                }

                sb.AppendLine(
                    $"\t\t\t[](std::vector<std::any> inParams)\n" +
                    $"\t\t\t{{\n" +
                    $"\t\t\t\tif (inParams.size() < {c.ParamTypes.Count()})\n" +
                    $"\t\t\t\t{{\n" +
                    $"\t\t\t\t\tthrow std::runtime_error(\"Missing reflected constructor [{t.Name}] parameters [{string.Join(",", c.ParamTypes.Select((p, i) => $"{p}"))}]\");\n" +
                    $"\t\t\t\t}}\n" +
                    $"\t\n" +
                    $"\t\t\t\treturn static_cast<void*>(\n" +
                    $"\t\t\t\t\tnew {t.Name}({paramUnpack})\n" +
                    $"\t\t\t\t);\n" +
                    $"\t\t\t}},"
                );
            }
            sb.AppendLine("\t\t},");

            sb.AppendLine("\t\t{");
            foreach (FunctionModel f in t.Functions)
            {
                var paramUnpack = string.Join(",", f.ParamTypes.Select((p, i) => $"\n\t\t\t\t\t\tstd::any_cast<{p}>(inParams.at({i}))"));

                if (f.ParamTypes.Count() > 0)
                {
                    paramUnpack += "\n\t\t\t\t\t";
                }

                sb.AppendLine(
                    $"\t\t\t{{\n" +
                    $"\t\t\t\t\"{f.Name}\",\n" +
                    $"\t\t\t\t\"{f.ReturnType}\",\n" +
                    $"\t\t\t\t{{{string.Join(" ,", f.ParamTypes.Select(p => $"\"{p}\""))}}},\n" +
                    $"\t\t\t\t[](void* inInstance, std::vector<std::any> inParams)\n" +
                    $"\t\t\t\t{{\n" +
                    $"\t\t\t\t\tif (inParams.size() < {f.ParamTypes.Count()})\n" +
                    $"\t\t\t\t\t{{\n" +
                    $"\t\t\t\t\t\tthrow std::runtime_error(\"Missing reflected method [{f.Name}] parameters [{string.Join(",", paramUnpack.Select((p, i) => $"{p}"))}]\");\n" +
                    $"\t\t\t\t\t}}\n" +
                    $"\t\n" +
                    $"\t\t\t\t\tstatic_cast<{t.Name}*>(inInstance)->{f.Name}({paramUnpack});\n" +
                    $"\t\t\t\t}}\n" +
                    $"\t\t\t}},"
                );
            }
            sb.AppendLine("\t\t},");

            sb.AppendLine("\t\t{");
            foreach (FieldModel f in t.Fields)
            {
                if (f.Names.Count <= 0)
                {
                    continue;
                }

                bool isReflected = allTypes.Any(rt => rt.Name == f.TypeName);

                sb.AppendLine(
                    $"\t\t\t{{\n" +
                    $"\t\t\t\t{{{string.Join(" ,", f.Names.Select(p => $"\"{p}\""))}}},\n" +
                    $"\t\t\t\t\"{f.TypeName}\",\n" +
                    $"\t\t\t\toffsetof({t.Name}, {f.Name}),\n" +
                    $"\t\t\t\tsizeof({(f.IsPointer ? "void*" : f.TypeName)}),\n" +
                    $"\t\t\t\tstd::type_index(typeid({f.TypeName})),\n" +
                    $"\t\t\t\t{(isReflected ? "true" : "false")},\n" +
                    $"\t\t\t\t{(f.IsPointer ? "true" : "false")}\n" +
                    $"\t\t\t}},"
                );
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine("\t)");
            sb.AppendLine(");");
            sb.AppendLine();

            sb.AppendLine("#if defined(__GNUC__) || defined(__clang__)");
            sb.AppendLine("#   pragma GCC diagnostic pop");
            sb.AppendLine("#endif");
            sb.AppendLine();
        }
    }
}