// AUTO-GENERATED by ReflectTool — do not edit by hand
#pragma once
#include "reflect.h"
#include "View.hpp"

// ── Class: View
inline AutoRegisterType _reg_View(TypeInfo{
    "View", sizeof(View),
    { // fields
    },
    { // methods
    }
});

