name: Documentation
on:
    push:
        branches: [master]
        paths:
            - 'Includes/Chicane/**.hpp'
            - 'Scripts/Documentation/Helper.py'
            - 'Scripts/Documentation.sh'
            - 'Scripts/Documentation.bat'
            - 'Doxyfile'
    workflow_dispatch:
concurrency:
    group: documentation-bots
    cancel-in-progress: false
jobs:
    build:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        defaults:
            run:
                working-directory: ./Scripts
        steps:
            - name: Setup Checkout
              uses: actions/checkout@v6

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.13'

            - name: Build XML
              uses: mattnotmitt/doxygen-action@1.12.0

            - name: Fix permissions
              working-directory: .
              run: |
                sudo chown -R $USER:$USER .docs
                chmod -R 755 .docs

            - name: Cleanup References
              working-directory: .
              run: rm -rf References

            - name: Build References
              run: bash Documentation.sh

            - name: Publish
              working-directory: .
              run: |
                cp -a References /tmp/References
                rm -rf References
                git fetch origin documentation
                git checkout -f -B documentation origin/documentation
                rm -rf References
                mv /tmp/References References

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                commit_message: 'docs: Updated documentation'
                file_pattern: 'References'
                skip_fetch: true
                skip_checkout: true
