name: Format
on:
    push:
        branches: [master]
        paths:
            - 'Includes/**.hpp'
            - 'Sources/**.cpp'
            - '.clang-format'
            - 'Scripts/Format.sh'
            - '.github/workflows/format.yml'
    workflow_dispatch:
concurrency:
    group: master-bots
    cancel-in-progress: false
jobs:
    build:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        steps:
            - name: Setup Checkout
              uses: actions/checkout@v6

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.13'

            - name: Install clang-format
              run: pip install clang-format==21.1.8

            - name: Run script
              run: bash Scripts/Format.sh

            - name: Rebase onto master
              run: |
                git fetch origin master
                git pull --rebase --autostash origin master

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                commit_message: 'style: Updated code format'
                file_pattern: |
                  Includes/
                  Sources/
                skip_fetch: true
                skip_checkout: true
